### ISSUE TITLE
Editing rights on the wiki

### ISSUE THREAD

**Issue by animeshsingh** [cdfoundation/sig-mlops#2]
https://lists.cd.foundation/g/sig-mlops 

Dont thinks I have editing right there @danlopez00 ?

**Comment by danlopez00** [comment]
I added the default page. Let me know if you see edit rights

**Comment by animeshsingh** [comment]
@danlopez00 still don't see it, and beyond the wiki, want to be able to edit the first page itself for mlops-sig.

**Comment by danlopez00** [comment]
elevated your repo permissions... give it a shot a let me know if that works

**Comment by danlopez00** [comment]
![image](https://user-images.githubusercontent.com/727396/73499871-27bb2700-4376-11ea-9095-4700a85e3cf4.png)

you and Kara have admin rights now to this repo
