### ISSUE TITLE
[Suggestion] Enable GitHub Discussions

### ISSUE THREAD

**Issue by unfor19** [cdfoundation/sig-mlops#43]
As a DevOps engineer/consultant, I'd love to learn more about ML-Ops. I think that having a "forum" (so 90s) would be great for tracking interesting discussions around the subject.

Enabling [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) is a good start. You can start with the basic categories - General, Ideas, Q&A, Show and tell.

**Comment by michaelneale** [comment]
interesting idea - how did you discover this @unfor19 ? 

The CDF has various slack/mailing list things, the mailing list uses google groups, but doesn't seem heavily used.

**Comment by unfor19** [comment]
I investigated the Settings menu in one of my repositories and found it :)

**Comment by michaelneale** [comment]
@unfor19 most of the current discussion happens in slack I think

**Comment by tracymiranda** [comment]
We are using github discussions for some other repos e.g. end user council https://github.com/cdfoundation/end-user-council/discussions.

If mlops folks are happy to set topics and keep an eye on it then happy to enable it for the group.

**Comment by tdcox** [comment]
Thanks. We are going to stick with developing the Slack community for now.

**Comment by jhadjar** [comment]
@tdcox Which one? Or is it yet to be created? There's one here https://mlops.community and they have a Slack workspace.

@unfor19 Have you checked that one out as well?

**Comment by tdcox** [comment]
@jhadjar Join [this group](https://join.slack.com/t/cdeliveryfdn/shared_invite/zt-ao8y4qhd-BQcTUg5l7m0HxXyBvJrT4w) and use the #sig-mlops channel.

The focus of this group is on ensuring that appropriate tooling exists to support the needs of the MLOps methodology, so we don’t really focus much on teaching MLOps itself.
