### ISSUE TITLE
Agenda Item: Proposal to focus SIG activities on producing MLOps Roadmap

### ISSUE THREAD

**Issue by tdcox** [cdfoundation/sig-mlops#5]
I would like to formally propose that we focus the activities of the SIG upon collaboratively producing a Roadmap document for MLOps, on an annual cadence.

I suggest that we devote a proportion of each year to gather the key challenges facing the community in the MLOps space, spell out the technology requirements associated with each challenge and consider potential solutions that might be adopted.

Once collated and agreed, this document can then be published and shared as the basis for efficient pre-competitive collaboration on core issues common across the community that will offer maximal benefits to customers if resolved.

It would probably make sense to look ahead five years at this stage and begin to anticipate capabilities that will be required by customers during that period.

I propose the following as a potential template for the structure of the roadmap and I have included some example challenges to give a feel for how we might want to shape the document over the coming year:

https://docs.google.com/document/d/15fhsarEYbXk1yeqTo6KbLArxJuRh4JbgMU3GBpSd-8Y/edit?usp=sharing

We can convert to a more appropriate format for collaborative editing if the proposal is adopted.

**Comment by visenger** [comment]
@tdcox thank you for the roadmap. 
I would really like to have a glossary, where some definitions, such as "Machine Learning and Data Science assets", could be defined. Thanks!
